spring.datasource.url=jdbc:postgresql://localhost:5432/foodblog
spring.datasource.username=postgres
spring.datasource.password=Suj@y2011
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
foodblog.jwt.secret=9a67473d72b22f676442656d263a6a246a646c243a786e32646675686e626b64
foodblog.jwt.expiration=86400000
